require 'artemis_api/client'
require 'artemis_api/model'
require 'artemis_api/facility'
require 'artemis_api/user'
require 'artemis_api/version'
require 'artemis_api/zone'
require 'artemis_api/organization'
require 'artemis_api/batch'
require 'artemis_api/completion'
require 'artemis_api/discard'
require 'artemis_api/harvest'
require 'artemis_api/seeding_unit'
require 'artemis_api/harvest_unit'
require 'artemis_api/resource_unit'
require 'artemis_api/crop_variety'
require 'artemis_api/item'
require 'artemis_api/subscription'
require 'artemis_api/stage'
require 'artemis_api/sub_stage'
require 'artemis_api/custom_fields'
require 'artemis_api/custom_data'

module ArtemisApi
  # Your code goes here...
end
